# Generated by Django 5.1.1 on 2024-11-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_user_alter_account_user_alter_financialgoal_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
